# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20161221_0959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='karma',
            unique_together=set([('owner', 'giver')]),
        ),
    ]
