# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20161221_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.ManyToManyField(through='catalog.Karma', to=settings.AUTH_USER_MODEL),
        ),
    ]
